<a href="https://colab.research.google.com/github/juhumkwon/Defense_Cloud/blob/main/4_4_naive_bayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy scikit-learn

In [ ]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# 데이터셋 (간단한 예제용 텍스트 데이터)
documents = [
    "I love programming",  # 긍정
    "Python is amazing",   # 긍정
    "I hate bugs",         # 부정
    "Debugging is fun",    # 긍정
    "I dislike errors",    # 부정
    "Coding is awesome",   # 긍정
    "I don't like debugging",  # 부정
    "Programming is great"  # 긍정
]

# 레이블 (1: 긍정, 0: 부정)
labels = [1, 1, 0, 1, 0, 1, 0, 1]

# 텍스트 데이터를 벡터로 변환 (단어 카운트를 사용)
vectorizer = CountVectorizer() # 텍스트 데이터를 숫자로 변환하는 도구인 CountVectorizer를 초기화하는 과정
X = vectorizer.fit_transform(documents) # fit_transform() → 어휘 사전 생성 + 벡터 변환

# 학습용과 테스트용 데이터 분리
X_train, X_test, y_train, y_test = train_test_split(X, labels, test_size=0.3, random_state=42)

# Naive Bayes 분류기 모델 생성
nb_classifier = MultinomialNB()

# 모델 학습
nb_classifier.fit(X_train, y_train)

# 테스트 데이터 예측
y_pred = nb_classifier.predict(X_test)

# 정확도 평가
accuracy = accuracy_score(y_test, y_pred)
print(f"모델의 정확도: {accuracy * 100:.2f}%")


# 예측 결과 출력
# Get the indices of the test documents in the original documents list
test_indices = X_test.toarray().sum(axis=1).nonzero()[0] # toarray() 메서드는 **희소 행렬을 밀집 배열(Dense Array)**로 변환합니다.

# Use these indices to select the corresponding documents and predictions
for i, pred in zip(test_indices, y_pred):
    doc = documents[i]  # Get the document using its original index
    print(f"문서: {doc} -> 예측된 레이블: {'긍정' if pred == 1 else '부정'}")


모델의 정확도: 100.00%
문서: I love programming -> 예측된 레이블: 긍정
문서: Python is amazing -> 예측된 레이블: 긍정
문서: I hate bugs -> 예측된 레이블: 긍정


In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

# 문서 리스트
documents = [
    "I love machine learning",
    "Machine learning is amazing",
    "Deep learning is a subset of machine learning"
]

# CountVectorizer 초기화 및 변환
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(documents)

# 변환된 희소 행렬 출력
print(X)

# 희소 행렬을 배열로 변환하여 출력
print(X.toarray())

# 어휘 사전 확인
print(vectorizer.get_feature_names_out())


<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 13 stored elements and shape (3, 8)>
  Coords	Values
  (0, 4)	1
  (0, 5)	1
  (0, 3)	1
  (1, 5)	1
  (1, 3)	1
  (1, 2)	1
  (1, 0)	1
  (2, 5)	1
  (2, 3)	2
  (2, 2)	1
  (2, 1)	1
  (2, 7)	1
  (2, 6)	1
[[0 0 0 1 1 1 0 0]
 [1 0 1 1 0 1 0 0]
 [0 1 1 2 0 1 1 1]]
['amazing' 'deep' 'is' 'learning' 'love' 'machine' 'of' 'subset']
